micronaut:
  application:
    name: micronautHibernateValidator
  executors:
    io:
      type: fixed
      number-of-threads: 20
    scheduled:
      type: fixed
      number-of-threads: 20
netty:
  default:
    allocator:
      max-order: 3
